// sounds from various forders


~bufDrumkit = SoundFile.collectIntoBuffers(path: "/home/hellska/soundAndSamples/samples/Industrial-autoprodotti/*".standardizePath);
~soundFileDrumkit = SoundFile.collect(path: "/Volumes/ssdData/soundsAndSamples/Industrial-autoprodotti/*".standardizePath);

~ticGaber = SoundFile.collectIntoBuffers("/Volumes/ssdData/soundsAndSamples/tic_gaber/*".standardizePath);
~mwvoices900 = SoundFile.collectIntoBuffers("/Volumes/ssdData/soundsAndSamples/900-marghera-workers-voices/*".standardizePath);

~tzunami = SoundFile.collectIntoBuffers("/Volumes/ssdData/soundsAndSamples/tzunami/*".standardizePath);
~blo_samples = SoundFile.collectIntoBuffers("/Volumes/ssdData/soundsAndSamples/BLO/*".standardizePath);